# Generated by Django 6.0.3 on 2026-03-17 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="название книги"),
                ),
                ("author", models.CharField(max_length=200, verbose_name="автор")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("horror", "Horror"),
                            ("science", "Science"),
                            ("drama", "Drama"),
                            ("satire", "Satire"),
                            ("history", "History"),
                        ],
                        max_length=50,
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Прочитано/Не прочитано"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Рейтинг не может быть ниже 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="Рейтинг не может быть выше 5"
                            ),
                        ],
                        verbose_name="Рейтинг книги",
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, null=True, verbose_name="Отзыв"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
